/**:
  ros__parameters:
    roi_line:
      roi_up: [330, 360, 0, 640]
      roi_center: [390, 420, 0, 640]
      roi_down: [450, 480, 0, 640]
      scale: [0.1, 0.2, 0.7]
    roi_circle:
      x_min: 0
      x_max: 640
      y_min: 0
      y_max: 480
    roi_rect:
      x_min: 0
      x_max: 640
      y_min: 0
      y_max: 480
