/**:
  ros__parameters:
    filter1:
      name: scan
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.6
        upper_angle: 1.6
    filter2:
      name: box_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false   # if not specified defaults to false
        lower_threshold: 0.1             # if not specified defaults to 0.0
        upper_threshold: 8.0             # if not specified defaults to 100000.0
        lower_replacement_value: -.inf    # if not specified defaults to NaN
        upper_replacement_value: .inf     # if not specified defaults
